version: '3.8'

services:
  restoration-complete:
    image: claude-code-agent:latest
    container_name: tdd_phase_4_restore-restoration-complete
    environment:
      - AGENT_ROLE=restoration-complete
      - AGENT_TYPE=complete-cycle
      - PROJECT_NAME=tdd_phase_4_restoration
      - PROMPT_FILE=/prompts/tdd-restoration-automation.md
      - EXPECTED_TESTS=892
      - TARGET_PASS_RATE=100
      - TEST_COMMANDS=npx tsc --noEmit;npm run test:hooks:executive || true;npm run test:components:executive || true;npm run test:screens:executive || true;npm run test:cross-role || true;npm run test:integration:executive || true
      - MONITORING_PORT=3007
    volumes:
      - ../../volumes/tdd_phase_4_restore-restoration-complete:/workspace
      - ../../agents/prompts:/prompts:ro
      - ../../configs:/configs:ro
      - ../../volumes/communication:/communication
      - ../../volumes/communication/handoffs:/handoffs
      - ../../volumes/communication/progress:/progress
      - ../../volumes/communication/preservation:/preservation
    working_dir: /workspace
    command: /scripts/entrypoint-generic.sh
    networks:
      - tdd_phase_4_restoration_network
    deploy:
      resources:
        limits:
          memory: 4g
          cpus: '2'
    restart: on-failure:5
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

networks:
  tdd_phase_4_restoration_network:
    driver: bridge
    name: tdd_phase_4_restoration_network

volumes:
  restoration_shared:
    driver: local