# TDD Phase 3 Marketing Operations Configuration
# Multi-agent project for test-driven marketing system development

project:
  name: "marketing_operations"
  prefix: "tdd_phase_3"
  description: "TDD Phase 3: Marketing Operations with Content Workflows"
  max_restarts: 2
  test_pass_target: 85
  monitoring_port: 3003
  workspace_strategy: "unified"  # Options: unified (default), layer, isolated

agents:
  # RED Phase - Test Writers (Parallel)
  - name: "marketing-schema-tests"
    type: "test-writer"
    phase: "RED"
    depends_on: []
    test_command: "npm run test:schemas:marketing"
    prompt_file: "phase3-marketing-schema-tests.md"
    
  - name: "marketing-service-tests"
    type: "test-writer"
    phase: "RED"
    depends_on: []
    test_command: "npm run test:services:marketing"
    prompt_file: "phase3-marketing-service-tests.md"
    
  - name: "marketing-hooks-tests"
    type: "test-writer"
    phase: "RED"
    depends_on: []
    test_command: "npm run test:hooks:marketing"
    prompt_file: "phase3-marketing-hooks-tests.md"
    
  - name: "marketing-screens-tests"
    type: "test-writer"
    phase: "RED"
    depends_on: []
    test_command: "npm run test:screens:marketing"
    prompt_file: "phase3-marketing-screens-tests.md"
    
  - name: "marketing-components-tests"
    type: "test-writer"
    phase: "RED"
    depends_on: []
    test_command: "npm run test:components:marketing"
    prompt_file: "phase3-marketing-components-tests.md"
    
  - name: "marketing-integration-tests"
    type: "test-writer"
    phase: "RED"
    depends_on: []
    test_command: "npm run test:integration:marketing"
    prompt_file: "phase3-marketing-integration-tests.md"

  # GREEN Phase - Implementers (After RED phase completes)
  - name: "marketing-schema-impl"
    type: "implementer"
    phase: "GREEN"
    depends_on: ["marketing-schema-tests"]
    test_command: "npm run test:schemas:marketing"
    prompt_file: "phase3-marketing-schema-impl.md"
    
  - name: "marketing-service-impl"
    type: "implementer"
    phase: "GREEN"
    depends_on: ["marketing-service-tests", "marketing-schema-impl"]
    test_command: "npm run test:services:marketing"
    prompt_file: "phase3-marketing-service-impl.md"
    
  - name: "marketing-hooks-impl"
    type: "implementer"
    phase: "GREEN"
    depends_on: ["marketing-hooks-tests", "marketing-service-impl"]
    test_command: "npm run test:hooks:marketing"
    prompt_file: "phase3-marketing-hooks-impl.md"
    
  - name: "marketing-components-impl"
    type: "implementer"
    phase: "GREEN"
    depends_on: ["marketing-components-tests"]
    test_command: "npm run test:components:marketing"
    prompt_file: "phase3-marketing-components-impl.md"
    
  - name: "marketing-screens-impl"
    type: "implementer"
    phase: "GREEN"
    depends_on: ["marketing-screens-tests", "marketing-components-impl", "marketing-hooks-impl"]
    test_command: "npm run test:screens:marketing"
    prompt_file: "phase3-marketing-screens-impl.md"
    
  - name: "marketing-integration-impl"
    type: "implementer"
    phase: "GREEN"
    depends_on: ["marketing-integration-tests", "marketing-screens-impl"]
    test_command: "npm run test:integration:marketing"
    prompt_file: "phase3-marketing-integration-impl.md"

  # REFACTOR Phase - Optimization
  - name: "marketing-refactor"
    type: "refactor"
    phase: "REFACTOR"
    depends_on: ["marketing-integration-impl"]
    test_command: "npm run test:marketing:all"
    prompt_file: "phase3-marketing-refactor.md"

  # AUDIT Phase - Compliance
  - name: "marketing-audit"
    type: "audit"
    phase: "AUDIT"
    depends_on: ["marketing-refactor"]
    test_command: "npm run validate:marketing:patterns"
    prompt_file: "phase3-marketing-audit.md"

  # Final Integration
  - name: "marketing-integration-final"
    type: "integration"
    phase: "INTEGRATION"
    depends_on: ["marketing-audit"]
    test_command: "npm run test:marketing:all"
    prompt_file: "phase3-marketing-integration-final.md"