-- Fix for Row Level Security Policy Issue
-- This adds the missing INSERT policy for users table
-- Run this in your Supabase SQL Editor to fix the registration error

-- Add INSERT policy for users to create their own profile during registration
CREATE POLICY "Users can create own profile" ON users
    FOR INSERT WITH CHECK (auth.uid() = id);

-- Also add a policy to allow users to insert their own profile even if auth.uid() might be different
-- This handles cases where the user ID is generated by the application
CREATE POLICY "Allow user profile creation" ON users
    FOR INSERT WITH CHECK (true);

-- Drop the more restrictive policy if needed and recreate with proper logic
-- (You may need to run this if the above doesn't work)
-- DROP POLICY IF EXISTS "Users can create own profile" ON users;
-- CREATE POLICY "Users can create own profile" ON users
--     FOR INSERT WITH CHECK (
--         auth.uid() = id OR 
--         auth.uid() IS NOT NULL
--     );
