# Safe Repository Integration Configuration
# Single-agent integration with safety monitoring
# Following existing TDD Phase 4 pattern

project:
  name: "repository_integration"
  prefix: "safe_integration"
  description: "Safe Repository Integration with Monitoring"
  max_restarts: 15
  test_pass_target: 100
  monitoring_port: 3011
  workspace_strategy: "shared"  # Works on main codebase

agents:
  - name: "repository-integration"
    type: "integration"
    depends_on: []
    test_command: "npm test"
    prompt_file: "safe-repository-integration.md"
    environment:
      - TARGET_REPO=${TARGET_REPO:-tdd_phase_4-decision-support}
      - SAFETY_MODE=enabled
      - AUTO_PAUSE_ON_VIOLATION=true