project:
  name: tdd_phase_4b_sequential
  description: "TDD Phase 4b - Sequential Executive Dashboard Integration"
  prefix: phase4b
  test_command: "timeout 120 npm test -- --passWithNoTests --forceExit --maxWorkers=2 || echo 'Tests: 0 passed, 0 failed'"
  pass_rate_target: 100
  max_cycles: 10

agents:
  # Sequential order - each depends on the previous
  - name: decision-support
    type: integration
    prompt_file: phase4b-decision-support.md
    depends_on: []  # No dependencies, starts first
    reference_repo: tdd_phase_4-decision-support
    
  - name: executive-components
    type: integration
    prompt_file: phase4b-executive-components.md
    depends_on: [decision-support]  # Waits for decision-support to reach 100%
    reference_repo: tdd_phase_4-executive-components
    
  - name: executive-hooks
    type: integration
    prompt_file: phase4b-executive-hooks.md
    depends_on: [executive-components]  # Waits for executive-components to reach 100%
    reference_repo: tdd_phase_4-executive-hooks
    
  - name: executive-screens
    type: integration
    prompt_file: phase4b-executive-screens.md
    depends_on: [executive-hooks]  # Waits for executive-hooks to reach 100%
    reference_repo: tdd_phase_4-executive-screens
    
  - name: cross-role-integration
    type: integration
    prompt_file: phase4b-cross-role-integration.md
    depends_on: [executive-screens]  # Final integration after all components
    reference_repo: tdd_phase_4-cross-role-integration

monitoring:
  dashboard_port: 3015
  enable_logs: true
  enable_metrics: true
  health_check_interval: 30

docker:
  network: phase4b-network
  volume_base: docker/volumes
  
# Handoff configuration
handoff:
  trigger: test_pass_rate  # Handoff when tests reach target
  required_pass_rate: 100  # Must reach 100% before handoff
  mode: maintenance_exit  # Exit to maintenance mode after success
  create_marker: true      # Create handoff marker file
  
# Sequential workflow enforcements
workflow:
  type: sequential
  allow_parallel: false
  enforce_dependencies: true
  validate_handoffs: true
  workspace_mode: unified  # All agents share same worktree
  
# Reference repository configuration
references:
  mount_path: /reference
  read_only: true
  validate_tests: true  # Ensure reference tests pass in integrated code