/**
 * Auto-generated Supabase schema types
 * Generated on: 2025-08-16T00:36:47.233Z
 * Project: okqjoyfnfpafjmeszygi
 * 
 * DO NOT EDIT THIS FILE DIRECTLY
 * Run 'npm run sync-schema' to update
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "12.2.12 (cd3cf9e)"
  }
  public: {
    Tables: {
      cart_items: {
        Row: {
          created_at: string | null
          id: string
          product_id: string
          quantity: number
          updated_at: string | null
          user_id: string
        }
        Insert: {
          created_at?: string | null
          id?: string
          product_id: string
          quantity: number
          updated_at?: string | null
          user_id: string
        }
        Update: {
          created_at?: string | null
          id?: string
          product_id?: string
          quantity?: number
          updated_at?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "cart_items_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "product_inventory"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "cart_items_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "cart_items_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      categories: {
        Row: {
          created_at: string | null
          description: string | null
          id: string
          image_url: string | null
          is_available: boolean | null
          name: string
          sort_order: number | null
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          description?: string | null
          id?: string
          image_url?: string | null
          is_available?: boolean | null
          name: string
          sort_order?: number | null
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          description?: string | null
          id?: string
          image_url?: string | null
          is_available?: boolean | null
          name?: string
          sort_order?: number | null
          updated_at?: string | null
        }
        Relationships: []
      }
      error_recovery_log: {
        Row: {
          attempts_made: number | null
          compensation_applied: boolean | null
          completed_at: string | null
          created_at: string | null
          error_type: string
          id: string
          metadata: Json | null
          operation: string
          order_id: string | null
          original_error: string | null
          recovery_strategy: string
          result_message: string | null
          retry_count: number | null
          status: string
          user_id: string | null
        }
        Insert: {
          attempts_made?: number | null
          compensation_applied?: boolean | null
          completed_at?: string | null
          created_at?: string | null
          error_type: string
          id?: string
          metadata?: Json | null
          operation?: string
          order_id?: string | null
          original_error?: string | null
          recovery_strategy: string
          result_message?: string | null
          retry_count?: number | null
          status?: string
          user_id?: string | null
        }
        Update: {
          attempts_made?: number | null
          compensation_applied?: boolean | null
          completed_at?: string | null
          created_at?: string | null
          error_type?: string
          id?: string
          metadata?: Json | null
          operation?: string
          order_id?: string | null
          original_error?: string | null
          recovery_strategy?: string
          result_message?: string | null
          retry_count?: number | null
          status?: string
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "error_recovery_log_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "order_summary"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "error_recovery_log_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
        ]
      }
      inventory_logs: {
        Row: {
          change_type: string
          changed_by: string | null
          created_at: string | null
          id: string
          new_quantity: number
          previous_quantity: number
          product_id: string
          quantity_change: number
          reason: string | null
        }
        Insert: {
          change_type: string
          changed_by?: string | null
          created_at?: string | null
          id?: string
          new_quantity: number
          previous_quantity: number
          product_id: string
          quantity_change: number
          reason?: string | null
        }
        Update: {
          change_type?: string
          changed_by?: string | null
          created_at?: string | null
          id?: string
          new_quantity?: number
          previous_quantity?: number
          product_id?: string
          quantity_change?: number
          reason?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "inventory_logs_changed_by_fkey"
            columns: ["changed_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "inventory_logs_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "product_inventory"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "inventory_logs_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
        ]
      }
      no_show_log: {
        Row: {
          cancellation_reason: string | null
          detected_at: string | null
          grace_period_minutes: number | null
          id: string
          metadata: Json | null
          notification_sent: boolean | null
          order_id: string
          original_pickup_date: string
          original_pickup_time: string
          processed_at: string | null
          processing_status: string
          stock_restoration_applied: boolean | null
          user_id: string
        }
        Insert: {
          cancellation_reason?: string | null
          detected_at?: string | null
          grace_period_minutes?: number | null
          id?: string
          metadata?: Json | null
          notification_sent?: boolean | null
          order_id: string
          original_pickup_date: string
          original_pickup_time: string
          processed_at?: string | null
          processing_status?: string
          stock_restoration_applied?: boolean | null
          user_id: string
        }
        Update: {
          cancellation_reason?: string | null
          detected_at?: string | null
          grace_period_minutes?: number | null
          id?: string
          metadata?: Json | null
          notification_sent?: boolean | null
          order_id?: string
          original_pickup_date?: string
          original_pickup_time?: string
          processed_at?: string | null
          processing_status?: string
          stock_restoration_applied?: boolean | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "no_show_log_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "order_summary"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "no_show_log_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
        ]
      }
      notification_log: {
        Row: {
          created_at: string | null
          customer_email: string | null
          customer_name: string | null
          customer_phone: string | null
          delivered_at: string | null
          delivery_method: string
          error_message: string | null
          id: string
          message_content: string | null
          metadata: Json | null
          notification_type: string
          order_id: string | null
          retry_count: number | null
          sent_at: string | null
          status: string
          user_id: string | null
        }
        Insert: {
          created_at?: string | null
          customer_email?: string | null
          customer_name?: string | null
          customer_phone?: string | null
          delivered_at?: string | null
          delivery_method?: string
          error_message?: string | null
          id?: string
          message_content?: string | null
          metadata?: Json | null
          notification_type: string
          order_id?: string | null
          retry_count?: number | null
          sent_at?: string | null
          status?: string
          user_id?: string | null
        }
        Update: {
          created_at?: string | null
          customer_email?: string | null
          customer_name?: string | null
          customer_phone?: string | null
          delivered_at?: string | null
          delivery_method?: string
          error_message?: string | null
          id?: string
          message_content?: string | null
          metadata?: Json | null
          notification_type?: string
          order_id?: string | null
          retry_count?: number | null
          sent_at?: string | null
          status?: string
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "notification_log_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "order_summary"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notification_log_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
        ]
      }
      notification_logs: {
        Row: {
          channels_attempted: string[]
          channels_failed: string[]
          channels_sent: string[]
          created_at: string
          customer_email: string
          id: string
          notification_type: string
          order_id: string | null
          template_body: string
          template_title: string
          updated_at: string
        }
        Insert: {
          channels_attempted?: string[]
          channels_failed?: string[]
          channels_sent?: string[]
          created_at?: string
          customer_email: string
          id?: string
          notification_type: string
          order_id?: string | null
          template_body: string
          template_title: string
          updated_at?: string
        }
        Update: {
          channels_attempted?: string[]
          channels_failed?: string[]
          channels_sent?: string[]
          created_at?: string
          customer_email?: string
          id?: string
          notification_type?: string
          order_id?: string | null
          template_body?: string
          template_title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "notification_logs_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "order_summary"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notification_logs_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
        ]
      }
      order_items: {
        Row: {
          created_at: string | null
          id: string
          order_id: string
          product_id: string
          product_name: string
          quantity: number
          total_price: number
          unit_price: number
        }
        Insert: {
          created_at?: string | null
          id?: string
          order_id: string
          product_id: string
          product_name: string
          quantity: number
          total_price: number
          unit_price: number
        }
        Update: {
          created_at?: string | null
          id?: string
          order_id?: string
          product_id?: string
          product_name?: string
          quantity?: number
          total_price?: number
          unit_price?: number
        }
        Relationships: [
          {
            foreignKeyName: "order_items_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "order_summary"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "order_items_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "order_items_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "product_inventory"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "order_items_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
        ]
      }
      orders: {
        Row: {
          created_at: string | null
          customer_email: string
          customer_name: string
          customer_phone: string
          delivery_address: string | null
          fulfillment_type: string
          id: string
          notes: string | null
          payment_method: string | null
          payment_status: string | null
          pickup_date: string | null
          pickup_time: string | null
          qr_code_data: string | null
          special_instructions: string | null
          status: string
          subtotal: number
          tax_amount: number
          total_amount: number
          updated_at: string | null
          user_id: string | null
        }
        Insert: {
          created_at?: string | null
          customer_email: string
          customer_name: string
          customer_phone: string
          delivery_address?: string | null
          fulfillment_type?: string
          id?: string
          notes?: string | null
          payment_method?: string | null
          payment_status?: string | null
          pickup_date?: string | null
          pickup_time?: string | null
          qr_code_data?: string | null
          special_instructions?: string | null
          status?: string
          subtotal: number
          tax_amount?: number
          total_amount: number
          updated_at?: string | null
          user_id?: string | null
        }
        Update: {
          created_at?: string | null
          customer_email?: string
          customer_name?: string
          customer_phone?: string
          delivery_address?: string | null
          fulfillment_type?: string
          id?: string
          notes?: string | null
          payment_method?: string | null
          payment_status?: string | null
          pickup_date?: string | null
          pickup_time?: string | null
          qr_code_data?: string | null
          special_instructions?: string | null
          status?: string
          subtotal?: number
          tax_amount?: number
          total_amount?: number
          updated_at?: string | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "orders_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      pickup_reschedule_log: {
        Row: {
          approved_at: string | null
          approved_by: string | null
          created_at: string | null
          id: string
          new_pickup_date: string
          new_pickup_time: string
          order_id: string
          original_pickup_date: string | null
          original_pickup_time: string | null
          reason: string | null
          rejection_reason: string | null
          requested_by: string
          status: string
          user_id: string
        }
        Insert: {
          approved_at?: string | null
          approved_by?: string | null
          created_at?: string | null
          id?: string
          new_pickup_date: string
          new_pickup_time: string
          order_id: string
          original_pickup_date?: string | null
          original_pickup_time?: string | null
          reason?: string | null
          rejection_reason?: string | null
          requested_by: string
          status?: string
          user_id: string
        }
        Update: {
          approved_at?: string | null
          approved_by?: string | null
          created_at?: string | null
          id?: string
          new_pickup_date?: string
          new_pickup_time?: string
          order_id?: string
          original_pickup_date?: string | null
          original_pickup_time?: string | null
          reason?: string | null
          rejection_reason?: string | null
          requested_by?: string
          status?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "pickup_reschedule_log_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "order_summary"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "pickup_reschedule_log_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
        ]
      }
      products: {
        Row: {
          category: string
          category_id: string
          created_at: string | null
          description: string
          id: string
          image_url: string | null
          is_available: boolean | null
          is_bundle: boolean | null
          is_pre_order: boolean | null
          is_weekly_special: boolean | null
          max_pre_order_quantity: number | null
          min_pre_order_quantity: number | null
          name: string
          nutrition_info: Json | null
          pre_order_available_date: string | null
          price: number
          seasonal_availability: boolean | null
          sku: string | null
          stock_quantity: number | null
          tags: string[] | null
          unit: string | null
          updated_at: string | null
          weight: number | null
        }
        Insert: {
          category: string
          category_id: string
          created_at?: string | null
          description: string
          id?: string
          image_url?: string | null
          is_available?: boolean | null
          is_bundle?: boolean | null
          is_pre_order?: boolean | null
          is_weekly_special?: boolean | null
          max_pre_order_quantity?: number | null
          min_pre_order_quantity?: number | null
          name: string
          nutrition_info?: Json | null
          pre_order_available_date?: string | null
          price: number
          seasonal_availability?: boolean | null
          sku?: string | null
          stock_quantity?: number | null
          tags?: string[] | null
          unit?: string | null
          updated_at?: string | null
          weight?: number | null
        }
        Update: {
          category?: string
          category_id?: string
          created_at?: string | null
          description?: string
          id?: string
          image_url?: string | null
          is_available?: boolean | null
          is_bundle?: boolean | null
          is_pre_order?: boolean | null
          is_weekly_special?: boolean | null
          max_pre_order_quantity?: number | null
          min_pre_order_quantity?: number | null
          name?: string
          nutrition_info?: Json | null
          pre_order_available_date?: string | null
          price?: number
          seasonal_availability?: boolean | null
          sku?: string | null
          stock_quantity?: number | null
          tags?: string[] | null
          unit?: string | null
          updated_at?: string | null
          weight?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "products_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "categories"
            referencedColumns: ["id"]
          },
        ]
      }
      users: {
        Row: {
          address: string | null
          created_at: string | null
          email: string
          id: string
          name: string
          phone: string | null
          role: string
          updated_at: string | null
        }
        Insert: {
          address?: string | null
          created_at?: string | null
          email: string
          id?: string
          name: string
          phone?: string | null
          role?: string
          updated_at?: string | null
        }
        Update: {
          address?: string | null
          created_at?: string | null
          email?: string
          id?: string
          name?: string
          phone?: string | null
          role?: string
          updated_at?: string | null
        }
        Relationships: []
      }
    }
    Views: {
      order_summary: {
        Row: {
          created_at: string | null
          customer_email: string | null
          customer_name: string | null
          id: string | null
          item_count: number | null
          pickup_date: string | null
          pickup_time: string | null
          products: string | null
          status: string | null
          total_amount: number | null
        }
        Relationships: []
      }
      product_inventory: {
        Row: {
          category: string | null
          category_name: string | null
          created_at: string | null
          id: string | null
          is_available: boolean | null
          name: string | null
          price: number | null
          stock_quantity: number | null
          tags: string[] | null
        }
        Relationships: []
      }
    }
    Functions: {
      decrement_product_stock: {
        Args: { product_id: string; quantity_to_subtract: number }
        Returns: undefined
      }
      increment_product_stock: {
        Args: { product_id: string; quantity_to_add: number }
        Returns: undefined
      }
      process_no_show_atomic: {
        Args: { input_grace_period_minutes?: number; input_order_id: string }
        Returns: Json
      }
      recover_from_error_atomic: {
        Args: {
          input_error_type: string
          input_metadata?: Json
          input_operation?: string
          input_order_id?: string
          input_original_error?: string
          input_retry_count?: number
          input_user_id?: string
        }
        Returns: Json
      }
      reschedule_pickup_atomic: {
        Args: {
          input_new_pickup_date: string
          input_new_pickup_time: string
          input_order_id: string
          input_reason?: string
          input_requested_by?: string
          input_user_id: string
        }
        Returns: Json
      }
      send_notification_atomic: {
        Args: {
          input_customer_email?: string
          input_customer_name?: string
          input_customer_phone?: string
          input_delivery_method?: string
          input_message_content?: string
          input_metadata?: Json
          input_notification_type: string
          input_order_id?: string
          input_user_id: string
        }
        Returns: Json
      }
      submit_order_atomic: {
        Args: {
          p_customer_email: string
          p_customer_name: string
          p_customer_phone: string
          p_delivery_address?: string
          p_fulfillment_type: string
          p_order_id: string
          p_order_items: Json
          p_payment_method: string
          p_payment_status: string
          p_pickup_date?: string
          p_pickup_time?: string
          p_special_instructions?: string
          p_status?: string
          p_subtotal: number
          p_tax_amount: number
          p_total_amount: number
          p_user_id: string
        }
        Returns: Json
      }
      upsert_cart_item: {
        Args: {
          input_product_id: string
          input_quantity_to_add: number
          input_user_id: string
        }
        Returns: {
          created_at: string | null
          id: string
          product_id: string
          quantity: number
          updated_at: string | null
          user_id: string
        }[]
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
