version: '3.8'

services:
  # Foundation Layer - Schema (runs first)
  inventory-schema-agent:
    build: 
      context: ./agents
      dockerfile: Dockerfile
    container_name: inventory-schema-agent
    environment:
      - AGENT_NAME=inventory-schema
      - AGENT_TYPE=foundation
      - PHASE=2
      - MAX_RESTARTS=5
      - AGENT_PROMPT_FILE=/prompts/phase2-inventory-schema.md
    volumes:
      - ./volumes/tdd-phase-2-inventory-schema:/workspace:rw
      - ./volumes/communication:/shared:rw
      - ./agents/prompts:/prompts:ro
      - ./agents/phase2-entrypoint-enhanced.sh:/usr/local/bin/entrypoint-enhanced.sh:ro
      - ~/.claude:/home/agent/.claude:rw
    working_dir: /workspace
    entrypoint: ["/usr/local/bin/entrypoint-enhanced.sh"]
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER

  # Service Layer (depends on schema)
  inventory-services-agent:
    build: 
      context: ./agents
      dockerfile: Dockerfile
    container_name: inventory-services-agent
    environment:
      - AGENT_NAME=inventory-services
      - AGENT_TYPE=service
      - PHASE=2
      - MAX_RESTARTS=5
      - AGENT_PROMPT_FILE=/prompts/phase2-inventory-services.md
      - DEPENDS_ON=inventory-schema
    volumes:
      - ./volumes/tdd-phase-2-inventory-services:/workspace:rw
      - ./volumes/communication:/shared:rw
      - ./agents/prompts:/prompts:ro
      - ./agents/phase2-entrypoint-enhanced.sh:/usr/local/bin/entrypoint-enhanced.sh:ro
      - ~/.claude:/home/agent/.claude:rw
    working_dir: /workspace
    entrypoint: ["/usr/local/bin/entrypoint-enhanced.sh"]
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
    depends_on:
      - inventory-schema-agent

  # Hook Layer (depends on services)
  inventory-hooks-agent:
    build: 
      context: ./agents
      dockerfile: Dockerfile
    container_name: inventory-hooks-agent
    environment:
      - AGENT_NAME=inventory-hooks
      - AGENT_TYPE=hook
      - PHASE=2
      - MAX_RESTARTS=5
      - AGENT_PROMPT_FILE=/prompts/phase2-inventory-hooks.md
      - DEPENDS_ON=inventory-services
    volumes:
      - ./volumes/tdd-phase-2-inventory-hooks:/workspace:rw
      - ./volumes/communication:/shared:rw
      - ./agents/prompts:/prompts:ro
      - ./agents/phase2-entrypoint-enhanced.sh:/usr/local/bin/entrypoint-enhanced.sh:ro
      - ~/.claude:/home/agent/.claude:rw
    working_dir: /workspace
    entrypoint: ["/usr/local/bin/entrypoint-enhanced.sh"]
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
    depends_on:
      - inventory-services-agent

  # Screen Layer (depends on hooks)
  inventory-screens-agent:
    build: 
      context: ./agents
      dockerfile: Dockerfile
    container_name: inventory-screens-agent
    environment:
      - AGENT_NAME=inventory-screens
      - AGENT_TYPE=screen
      - PHASE=2
      - MAX_RESTARTS=5
      - AGENT_PROMPT_FILE=/prompts/phase2-inventory-screens.md
      - DEPENDS_ON=inventory-hooks
    volumes:
      - ./volumes/tdd-phase-2-inventory-screens:/workspace:rw
      - ./volumes/communication:/shared:rw
      - ./agents/prompts:/prompts:ro
      - ./agents/phase2-entrypoint-enhanced.sh:/usr/local/bin/entrypoint-enhanced.sh:ro
      - ~/.claude:/home/agent/.claude:rw
    working_dir: /workspace
    entrypoint: ["/usr/local/bin/entrypoint-enhanced.sh"]
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
    depends_on:
      - inventory-hooks-agent

  # Integration Layer (depends on all)
  inventory-integration-agent:
    build: 
      context: ./agents
      dockerfile: Dockerfile
    container_name: inventory-integration-agent
    environment:
      - AGENT_NAME=inventory-integration
      - AGENT_TYPE=integration
      - PHASE=2
      - MAX_RESTARTS=5
      - AGENT_PROMPT_FILE=/prompts/phase2-inventory-integration.md
      - DEPENDS_ON=inventory-schema,inventory-services,inventory-hooks,inventory-screens
    volumes:
      - ./volumes/tdd-phase-2-inventory-integration:/workspace:rw
      - ./volumes/communication:/shared:rw
      - ./agents/prompts:/prompts:ro
      - ./agents/phase2-entrypoint-enhanced.sh:/usr/local/bin/entrypoint-enhanced.sh:ro
      - ~/.claude:/home/agent/.claude:rw
    working_dir: /workspace
    entrypoint: ["/usr/local/bin/entrypoint-enhanced.sh"]
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
    depends_on:
      - inventory-screens-agent

  # Phase 2 Monitoring
  phase2-monitoring:
    build:
      context: ./monitoring
      dockerfile: Dockerfile
    container_name: phase2-monitoring
    environment:
      - PORT=3002
      - PHASE=2
    volumes:
      - ./volumes/communication:/shared:rw
      - ./monitoring/analyze-logs.sh:/app/analyze-logs.sh:ro
      - ~/.claude:/home/monitor/.claude:rw
    ports:
      - "3002:3002"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

# Networks and volumes
networks:
  default:
    name: phase2-network

volumes:
  phase2-data:
    driver: local