version: '3.8'

services:
# TEMPLATE: This section will be generated per agent
# AGENT_TEMPLATE_START
  AGENT_NAME-agent:
    build: 
      context: ./agents
      dockerfile: Dockerfile
    container_name: AGENT_NAME-agent
    environment:
      - AGENT_NAME=AGENT_NAME
      - AGENT_TYPE=AGENT_TYPE
      - PROJECT_NAME=PROJECT_NAME
      - PROJECT_DESCRIPTION=PROJECT_DESCRIPTION
      - MAX_RESTARTS=MAX_RESTARTS_VALUE
      - TARGET_PASS_RATE=TARGET_PASS_RATE_VALUE
      - TEST_COMMAND=TEST_COMMAND
      - AGENT_PROMPT_FILE=/prompts/PROMPT_FILE
      - DEPENDS_ON=DEPENDS_ON_LIST
    volumes:
      - ./volumes/PROJECT_PREFIX-AGENT_NAME:/workspace:rw
      - ./volumes/communication:/shared:rw
      - ./agents/prompts:/prompts:ro
      - ./templates/entrypoint-generic.sh:/usr/local/bin/entrypoint-enhanced.sh:ro
      - ~/.claude:/home/agent/.claude:rw
    working_dir: /workspace
    entrypoint: ["/usr/local/bin/entrypoint-enhanced.sh"]
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
    depends_on:
      - DEPENDS_ON_AGENTS
# AGENT_TEMPLATE_END

  # Monitoring Container
  PROJECT_PREFIX-monitoring:
    build:
      context: ./monitoring
      dockerfile: Dockerfile
    container_name: PROJECT_PREFIX-monitoring
    environment:
      - PORT=MONITORING_PORT
      - PROJECT=PROJECT_NAME
    volumes:
      - ./volumes/communication:/shared:rw
      - ./monitoring/analyze-logs.sh:/app/analyze-logs.sh:ro
      - ~/.claude:/home/monitor/.claude:rw
    ports:
      - "MONITORING_PORT:MONITORING_PORT"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:MONITORING_PORT/health"]
      interval: 30s
      timeout: 10s
      retries: 3

# Networks and volumes
networks:
  default:
    name: PROJECT_PREFIX-network

volumes:
  PROJECT_PREFIX-data:
    driver: local